message-mojang-offline=&5[&2AlwaysOnline&5]&a Mojang servers are now offline!

mojang-server-status=false

xpaw-status=false

config_version=5

###################################################
#
#              SLEETLA DEVELOPMENT
#
###################################################
#
#              ALL RIGHTS RESERVED
#
###################################################
