name: ThrowOnline
version: 1.1
main: me.sleetla.ao.spigot.SpigotLoader
author: Sleetla
website: sleetla.pro
commands:
    throwonline:
        description: Yo boi Sleetla's base command
        permission: *
        usage: /throwo
        aliases: [to]
